import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner/banner";
import NavBar from "@/components/navbar/navbar";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={`${styles.page}`}>
				<h1>Netflix</h1>
				<NavBar />
				<Banner
					title="Clifford the red dog"
					subTitle="a very cute dog"
					imgUrl="/static/clifford.webp"
				/>
				{/* <Card/> */}
			</div>
		</>
	);
}
