import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner/banner";
import NavBar from "@/components/navbar/navbar";
import SectionCards from "@/components/card/section-cards";

import {
	getVideos,
	// 	getPopularVideos,
	// 	getWatchItAgainVideos,
} from "../lib/videos";

export async function getServerSideProps() {
	const disneyVideos = getVideos();
	return { props: { disneyVideos } };
}

export default function Home({ disneyVideos }) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={`${styles.page}`}>
				<NavBar />
				<Banner
					title="Clifford the red dog"
					subTitle="a very cute dog"
					imgUrl="/static/clifford.webp"
				/>
				<div className={styles.sectionWrapper}>
					<SectionCards title="Disney" videos={disneyVideos} size="large" />
					{/* <Card imgUrl="/static/clifford.webp" size="large" />
				<Card imgUrl="/static/clifford.webp" size="medium" />
				<Card imgUrl="/static/clifford.webp" size="small" /> */}
				</div>
			</div>
		</>
	);
}
